version: "3.9"
services:
    www:
        build: php
        image: php:8.0-apache
        container_name: www_morpion
        ports:
            - "8820:80"
        volumes:
            - ./php/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
        restart: always
        networks:
            - dev
   
networks:
    dev:

volumes:
    db-data:
